import React, { useState, useMemo } from 'react';
import { ChevronLeft, ChevronRight, Calendar as CalendarIcon, Download, Users, Clock, Loader, Eye } from 'lucide-react';
import type { Event } from '../services/eventService';
import { attendanceService } from '../services/attendanceService';
import { memberService } from '../services/memberService';

interface CalendarProps {
  events: Event[];
  isMobile?: boolean;
}

interface EventDetailsModalProps {
  event: Event | null;
  isOpen: boolean;
  onClose: () => void;
  onExportAttendance: (event: Event, format: 'csv' | 'pdf') => void;
  exportLoading: boolean;
  isMobile?: boolean;
}

const EventDetailsModal: React.FC<EventDetailsModalProps> = ({ 
  event, 
  isOpen, 
  onClose, 
  onExportAttendance, 
  exportLoading,
  isMobile = false
}) => {
  if (!isOpen || !event) return null;

  const eventTypeDisplay = event.eventType === 'sunday_service' ? 'Sunday Service' : 'Custom Event';
  const eventDate = new Date(event.date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const isPastEvent = new Date(event.date) < new Date();

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className={`bg-white rounded-2xl shadow-xl w-full ${
        isMobile ? 'max-h-[90vh] overflow-y-auto' : 'max-w-md'
      }`}>
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <div className="flex items-center space-x-3">
            <div className={`p-2 rounded-xl ${
              isPastEvent ? 'bg-green-100' : 'bg-blue-100'
            }`}>
              <CalendarIcon className={`h-6 w-6 ${
                isPastEvent ? 'text-green-600' : 'text-blue-600'
              }`} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">Event Details</h2>
              <p className="text-gray-500 text-sm">
                {isPastEvent ? 'Past Event - Reports Available' : 'Upcoming Event'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-xl transition-colors"
          >
            <span className="text-2xl text-gray-500">×</span>
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Event Information */}
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-gray-900">{event.name}</h3>
              <p className="text-gray-600">{eventTypeDisplay}</p>
            </div>

            <div className="space-y-3">
              <div className="flex items-center space-x-3 p-3 bg-gray-50 rounded-xl">
                <Clock className="h-5 w-5 text-gray-400" />
                <div>
                  <p className="text-sm font-medium text-gray-500">Date</p>
                  <p className="text-gray-900">{eventDate}</p>
                </div>
              </div>

              <div className="flex items-center space-x-3 p-3 bg-gray-50 rounded-xl">
                <Users className="h-5 w-5 text-gray-400" />
                <div>
                  <p className="text-sm font-medium text-gray-500">Event Type</p>
                  <p className="text-gray-900 capitalize">{eventTypeDisplay}</p>
                </div>
              </div>

              {event.autoGenerated && (
                <div className="flex items-center space-x-3 p-3 bg-blue-50 rounded-xl">
                  <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                  <div>
                    <p className="text-sm font-medium text-blue-700">Auto-generated Event</p>
                  </div>
                </div>
              )}

              {isPastEvent && (
                <div className="flex items-center space-x-3 p-3 bg-green-50 rounded-xl">
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  <div>
                    <p className="text-sm font-medium text-green-700">Past Event - Reports Available</p>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Quick Actions */}
          {isPastEvent && (
            <div className="bg-green-50 border border-green-200 rounded-xl p-4">
              <h4 className="font-medium text-green-800 mb-2">Export Attendance Report</h4>
              <p className="text-sm text-green-700 mb-3">
                Download the complete attendance report for this event.
              </p>
              <div className={`grid ${isMobile ? 'grid-cols-1 gap-3' : 'grid-cols-2 gap-2'}`}>
                <button
                  onClick={() => onExportAttendance(event, 'csv')}
                  disabled={exportLoading}
                  className="bg-green-600 text-white px-4 py-3 rounded-xl hover:bg-green-700 transition-colors flex items-center justify-center font-medium disabled:opacity-50"
                >
                  {exportLoading ? (
                    <Loader className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Download className="h-4 w-4 mr-2" />
                  )}
                  CSV
                </button>
                <button
                  onClick={() => onExportAttendance(event, 'pdf')}
                  disabled={exportLoading}
                  className="bg-red-600 text-white px-4 py-3 rounded-xl hover:bg-red-700 transition-colors flex items-center justify-center font-medium disabled:opacity-50"
                >
                  {exportLoading ? (
                    <Loader className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Download className="h-4 w-4 mr-2" />
                  )}
                  PDF
                </button>
              </div>
            </div>
          )}

          {!isPastEvent && (
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
              <div className="flex items-center mb-2">
                <Eye className="h-5 w-5 text-blue-600 mr-2" />
                <h4 className="font-medium text-blue-800">Upcoming Event</h4>
              </div>
              <p className="text-sm text-blue-700">
                Attendance reports will be available after the event date.
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex space-x-3 p-6 border-t border-gray-200">
          <button
            onClick={onClose}
            className="flex-1 bg-gray-600 text-white px-4 py-3 rounded-xl hover:bg-gray-700 transition-colors font-medium"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

const Calendar: React.FC<CalendarProps> = ({ events, isMobile = false }) => {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedEvent, setSelectedEvent] = useState<Event | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [exportLoading, setExportLoading] = useState(false);

  const calendarDays = useMemo(() => {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startDate = new Date(firstDay);
    startDate.setDate(startDate.getDate() - startDate.getDay());
    
    const endDate = new Date(lastDay);
    endDate.setDate(endDate.getDate() + (6 - endDate.getDay()));
    
    const days = [];
    const current = new Date(startDate);
    
    while (current <= endDate) {
      const date = new Date(current);
      const dayEvents = events.filter(event => {
        const eventDate = new Date(event.date);
        return eventDate.toDateString() === date.toDateString();
      });
      
      days.push({
        date: new Date(date),
        isCurrentMonth: date.getMonth() === month,
        isToday: date.toDateString() === new Date().toDateString(),
        events: dayEvents
      });
      
      current.setDate(current.getDate() + 1);
    }
    
    return days;
  }, [currentDate, events]);

  const navigateMonth = (direction: 'prev' | 'next') => {
    setCurrentDate(prev => {
      const newDate = new Date(prev);
      newDate.setMonth(prev.getMonth() + (direction === 'next' ? 1 : -1));
      return newDate;
    });
  };

  const handleEventClick = (event: Event) => {
    setSelectedEvent(event);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setSelectedEvent(null);
  };

  const handleExportAttendance = async (event: Event, format: 'csv' | 'pdf') => {
    try {
      setExportLoading(true);
      
      if (format === 'csv') {
        // Get attendance data for this event
        const attendanceResponse = await attendanceService.getEventAttendance(event.eventId);
        const attendanceData = attendanceResponse.attendance || [];

        // Get all members to include absent members in the report
        const membersResponse = await memberService.getMembers({ page: 1, limit: 1000 });
        const allMembers = membersResponse.members;

        // Create a map of present members for quick lookup
        const presentMembersMap = new Map();
        attendanceData.forEach(record => {
          if (record.attendance.status === 'present') {
            presentMembersMap.set(record.member.memberId, record);
          }
        });

        // Generate CSV content
        const headers = ['Name', 'Age Group', 'Gender', 'Residence', 'Status', 'Marked At'];
        
        const csvRows = allMembers.map(member => {
          const attendanceRecord = presentMembersMap.get(member.memberId);
          const status = attendanceRecord ? 'Present' : 'Absent';
          const markedAt = attendanceRecord ? 
            new Date(attendanceRecord.attendance.markedAt).toLocaleString() : 'N/A';

          return [
            `"${member.name}"`,
            member.ageGroup,
            member.gender,
            `"${member.residence}"`,
            status,
            markedAt
          ];
        });

        const csvContent = [
          headers.join(','),
          ...csvRows.map(row => row.join(','))
        ].join('\n');

        // Create and download file
        const blob = new Blob([csvContent], { type: 'text/csv' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `attendance-${event.name}-${event.date}.csv`.replace(/[^a-zA-Z0-9-_]/g, '_');
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
      } else if (format === 'pdf') {
        // For PDF export, you would typically call your backend service
        // This is a placeholder - implement based on your backend API
        const response = await attendanceService.exportEventReport(event.eventId, 'pdf');
        const blob = new Blob([response], { type: 'application/pdf' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `attendance-report-${event.name}-${event.date}.pdf`.replace(/[^a-zA-Z0-9-_]/g, '_');
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
      }

    } catch (error) {
      console.error('Failed to export attendance:', error);
      alert('Failed to export attendance report');
    } finally {
      setExportLoading(false);
    }
  };

  const monthYear = currentDate.toLocaleDateString('en-US', {
    month: 'long',
    year: 'numeric'
  });

  const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

  return (
    <>
      <div className={`bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden ${
        isMobile ? 'text-sm' : ''
      }`}>
        {/* Calendar Header */}
        <div className={`flex items-center justify-between ${
          isMobile ? 'p-4' : 'p-6'
        } border-b border-gray-200`}>
          <div className="flex items-center space-x-3">
            <CalendarIcon className={`${isMobile ? 'h-5 w-5' : 'h-6 w-6'} text-blue-600`} />
            <h3 className={`${isMobile ? 'text-base' : 'text-lg'} font-semibold text-gray-900`}>
              {monthYear}
            </h3>
          </div>
          <div className="flex space-x-2">
            <button
              onClick={() => navigateMonth('prev')}
              className="p-2 hover:bg-gray-100 rounded-xl transition-colors"
            >
              <ChevronLeft className="h-4 w-4 text-gray-600" />
            </button>
            <button
              onClick={() => setCurrentDate(new Date())}
              className="px-3 py-2 text-sm bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition-colors font-medium"
            >
              Today
            </button>
            <button
              onClick={() => navigateMonth('next')}
              className="p-2 hover:bg-gray-100 rounded-xl transition-colors"
            >
              <ChevronRight className="h-4 w-4 text-gray-600" />
            </button>
          </div>
        </div>

        {/* Calendar Grid */}
        <div className={isMobile ? 'p-2' : 'p-6'}>
          {/* Day Headers */}
          <div className="grid grid-cols-7 gap-1 mb-2">
            {dayNames.map(day => (
              <div key={day} className={`text-center font-medium text-gray-500 py-2 ${
                isMobile ? 'text-xs' : 'text-sm'
              }`}>
                {isMobile ? day.charAt(0) : day}
              </div>
            ))}
          </div>

          {/* Calendar Days */}
          <div className="grid grid-cols-7 gap-1">
            {calendarDays.map((day, index) => (
              <div
                key={index}
                className={`min-h-16 p-1 border border-gray-200 rounded-lg ${
                  day.isCurrentMonth ? 'bg-white' : 'bg-gray-50'
                } ${day.isToday ? 'ring-2 ring-blue-500 ring-inset' : ''} ${
                  day.date.getTime() < new Date().setHours(0,0,0,0) ? 'opacity-90' : ''
                } ${isMobile ? 'text-xs' : ''}`}
              >
                <div className="flex justify-between items-start mb-1">
                  <span
                    className={`font-medium ${
                      day.isToday
                        ? 'bg-blue-600 text-white rounded-full w-5 h-5 flex items-center justify-center text-xs'
                        : day.isCurrentMonth
                        ? day.date.getTime() < new Date().setHours(0,0,0,0)
                          ? 'text-gray-600' 
                          : 'text-gray-900'
                        : 'text-gray-400'
                    }`}
                  >
                    {day.date.getDate()}
                  </span>
                </div>

                {/* Events - Clickable */}
                <div className="space-y-0.5 max-h-12 overflow-y-auto">
                  {day.events.map((event, eventIndex) => {
                    const isPastEvent = new Date(event.date) < new Date();
                    return (
                      <button
                        key={eventIndex}
                        onClick={() => handleEventClick(event)}
                        className={`w-full text-left p-1 rounded transition-colors text-xs ${
                          isPastEvent
                            ? 'bg-green-100 text-green-800 hover:bg-green-200 border border-green-200'
                            : event.eventType === 'sunday_service'
                            ? 'bg-blue-100 text-blue-800 hover:bg-blue-200'
                            : 'bg-purple-100 text-purple-800 hover:bg-purple-200'
                        }`}
                      >
                        <div className="font-medium truncate">
                          {isMobile ? event.name.split(' ')[0] : event.name}
                        </div>
                        <div className="flex justify-between text-xs opacity-75 mt-0.5">
                          <span>
                            {event.eventType === 'sunday_service' ? 'Service' : 'Event'}
                          </span>
                          {isPastEvent && (
                            <span className="font-medium">Report</span>
                          )}
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Legend */}
        <div className="p-3 border-t border-gray-200 bg-gray-50">
          <div className={`flex flex-wrap gap-3 ${isMobile ? 'text-xs' : 'text-sm'}`}>
            <div className="flex items-center space-x-1">
              <div className="w-2 h-2 bg-green-100 border border-green-300 rounded"></div>
              <span className="text-gray-600">Past Events (Reports)</span>
            </div>
            <div className="flex items-center space-x-1">
              <div className="w-2 h-2 bg-blue-100 border border-blue-300 rounded"></div>
              <span className="text-gray-600">Sunday Services</span>
            </div>
            <div className="flex items-center space-x-1">
              <div className="w-2 h-2 bg-purple-100 border border-purple-300 rounded"></div>
              <span className="text-gray-600">Custom Events</span>
            </div>
          </div>
        </div>
      </div>

      {/* Event Details Modal */}
      <EventDetailsModal
        event={selectedEvent}
        isOpen={isModalOpen}
        onClose={handleCloseModal}
        onExportAttendance={handleExportAttendance}
        exportLoading={exportLoading}
        isMobile={isMobile}
      />
    </>
  );
};

export default Calendar;